# Generated by Django 4.2 on 2023-04-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('pattern', models.ImageField(upload_to='pattern_image/')),
                ('mini_pattern', models.ImageField(blank=True, upload_to='mini_pattern/')),
                ('pattern_description', models.TextField()),
                ('scheme', models.ImageField(upload_to='scheme_image/')),
                ('scheme_description', models.ImageField(upload_to='scheme_image/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pattern_lib.category')),
            ],
        ),
    ]
