# Generated by Django 4.2 on 2023-04-30 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_lib', '0002_alter_pattern_scheme_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='mini_pattern',
        ),
    ]
