# Generated by Django 4.2 on 2023-05-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_library', '0002_category_image_alter_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('definition', models.TextField()),
            ],
        ),
    ]
