# Generated by Django 4.2 on 2023-05-18 10:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_library', '0004_testrichtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrichtext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
