# Generated by Django 4.2 on 2023-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference3846',
            fields=[
                ('field_idrref', models.BinaryField(db_column='_idrref', primary_key=True, serialize=False)),
                ('field_version', models.IntegerField(db_column='_version')),
                ('field_marked', models.BooleanField(db_column='_marked')),
                ('field_predefinedid', models.BinaryField(db_column='_predefinedid')),
                ('field_parentidrref', models.BinaryField(db_column='_parentidrref')),
                ('field_folder', models.BooleanField(db_column='_folder')),
                ('field_code', models.TextField(db_column='_code')),
                ('field_description', models.TextField(db_column='_description')),
                ('field_fld3847', models.TextField(blank=True, db_column='_fld3847', null=True)),
                ('field_fld3848', models.TextField(blank=True, db_column='_fld3848', null=True)),
                ('field_fld3849', models.TextField(blank=True, db_column='_fld3849', null=True)),
                ('field_fld3850', models.TextField(blank=True, db_column='_fld3850', null=True)),
                ('field_fld3851', models.TextField(blank=True, db_column='_fld3851', null=True)),
                ('field_fld210', models.DecimalField(db_column='_fld210', decimal_places=0, max_digits=7)),
            ],
            options={
                'db_table': '_reference3846',
                'managed': False,
            },
        ),
    ]
